### ISSUE TITLE
installtool: Verify the new-content/old-content comparison has the desired result

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#17]
Verify the new-content/old-content comparison has the desired result.

For now, this means the post-install and pre-uninstall cases.

We leave it to our users to decide about whether to run the pre-uninstall sudo script for the old version or not when doing updates from one version of scoranop to another.

**Comment by lack** [comment]
This sounds to me like there are 2 test cases here:

1. Install soundcraft-utils, get the service working, then properly uninstall it, then install socranop, and validate everything works properly
2. Install soundcraft-utils, get the service working, then, without uninstalling it at all, install socranop and validate everything works properly (or has an appropriate error message if it doesn't)

Or did you have something else in mind for this issue?

**Comment by lack** [comment]
When running socranop-installtool --post, we should only suggest creating the udev rules or re-triggering udev if the proposed udev rules differ from what is already present on the system.
