### ISSUE TITLE
Drop Python 3.6 support (in late 2021-12)

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#2]
According to https://devguide.python.org/#status-of-python-branches, Python 3.6 has an End-of-life date of 2021-12-23.

So around christmas 2021, we can drop the requirement for supporting Python 3.6, and move the requirement up to 3.7 or 3.8:

  * Python 3.7 has End-of-life 2023-06-27
  * Python 3.8 has End-of-life 2024-10

**Comment by ndim** [comment]
Note that Debian 10 (Buster) having Python 3.7 means we are actually stuck with 3.7 for some time, and cannot require all those nice features introduced in Python 3.8: https://wiki.debian.org/Python#Supported_Python_Versions

**Comment by ndim** [comment]
FTR, wwitching to Python 3.7 as a minimum required version will allow us to use the new features introduced by 3.7: https://docs.python.org/3/whatsnew/3.7.html

**Comment by matthewarmand** [comment]
3.7 recently hit end of life. As of today, the earliest actively supported minor version of Python is 3.8, and elevating to that level would also fix this lament in `setup.py`: https://github.com/socratools/socranop/blob/main/setup.py#L8

> If we were to use importlib.metadata, we could move from setup.py to
 setup.cfg and get to information like the package version from the
 software package itself. Unfortunately, importlib.metadata is only
 available in Python >= 3.8, but we want to support Python 3.6.

**Comment by ndim** [comment]
Debian LTS for oldoldstable (Buster aka 10) appears to be scheduled  tolast until 2024-06-30, and that still has Python 3.7. Source: https://wiki.debian.org/LTS

**Comment by ndim** [comment]
FWIW, for the last few months, I have been trying (and failing) to actually set up a development environment and run and install socranop on my system (first Fedora 38 with Python 3.11, now Fedora 39 with Python 3.12). The `pipenv install` step fails.

So at this time, any actual tests and therefore changes are impossible on my side.

It might be possible to fix the `pipenv` stuff, or it might be possible to do something else, but that is additional work I need to do before I can do actual work on `socranop`.

**Comment by ndim** [comment]
For me personally, socranop could just require Python version >= 3.8 or even newer.

Python 3.8 already provides some features which I would have used but had to work around instead (see the checks from https://github.com/socratools/socranop/blob/main/contrib/sources/find-mistakes).

IIRC, the main reason for supporting Python 3.6 still was that someone important to this project were still running systems with Python 3.6. That person might have been @lack himself, and his systems might have been update during the last two years of nothing happening with socranop. But socranop always must support its developers' systems, regardless of how old they might be.

**Comment by lack** [comment]
Thanks ;)

Been meaning to come back and finish this, and I have no objections to dropping the older python version support!

**Comment by ndim** [comment]
@lack Just to be clear... which version requirement would you be OK with?

  * `>= 3.7` as you have recently prepared at your https://github.com/lack/socranop/tree/python-versionfix branch?
  * `>= 3.8` for `importlib.metadata`, `missing_ok=` and `@cached_property`, and for being the oldest version supported by Python upstream?
  * `>= 3.9` for Debian oldstable and whatever library features we might find 3.9 to introduce over 3.8?

I am fine with either `>= 3.8` or `>= 3.9`.

**Comment by lack** [comment]
Let's go all the way to 3.9!  I think that's pretty reasonable, meets my needs, And we can always reevaluate if anyone complains
