### ISSUE TITLE
Pass XDG_CONFIG_HOME to socranop-session-service via D-Bus?

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#22]
Should we pass the `XDG_CONFIG_HOME` environment variable to `socranop-session-service` via D-Bus, and then have `socranop-session-service` generate the location of the config dir and thus of the state file from it?

(This might more be a question of `dirs.py` somehow getting the `XDG_CONFIG_HOME` value from D-Bus instead of calling `os.getenv`, than it is a question of passing the env var via D-Bus.)

**Comment by lack** [comment]
Especially with this being a session dbus service now, are there any cases when the service's `XDG_CONFIG_HOME` environment value would not be what a user wants?

**Comment by ndim** [comment]
I doubt many people will set `XDG_CONFIG_HOME` explicitly, much less to different values for `socranop-{ctl,gui}` and for `socranop-session-service`.

Also, given that `socranop-session-service` is supposed to keep a mirror of the device state for all clients connecting to it, it can be argued that it is actually a *feature* that `socranop-session-service` uses a state file which is independent from the respective client's environment.

This still needs to be documented, though, e.g. in the man pages' sections on FILES.

**Comment by lack** [comment]
I agree it's a feature that the service has a single state file location that's independent of the client connecting.

So ye, let's not make that configurable via the API, but document the location.

**Comment by ndim** [comment]
This will be part of the man page/README/whatever documentation rewrite.
