### ISSUE TITLE
uevent() "add" branch uses non-existent property ID_PRODUCT_ID, breaks dbus.Client.WaitForDevice()

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#44]
I got a bit of help on `#systemd` from @grawity, who figured this one out quite quickly.

Apparently the name of the udev property containing a USB devices' 16bit hex `idProduct` (USB Spec name, and sysfs name) has been `ID_MODEL_ID` all along (https://github.com/systemd/systemd/blob/main/src/udev/udev-builtin-usb_id.c#L432-L439), *not* `ID_PRODUCT_ID`.

The only reason why our `uevent()` "add" branch ever worked in `soundcraft-utils` or `socranop` could have been that either

  * some part of the code previously used `get_sysfs_attr("idProduct")` (that would have been inside libgudev or libudev, which I find unlikely)
  * or we had a custom udev rule which set ID_PRODUCT_ID (which might have been part of some distro package until recently)

Anyway, with the name of this udev property having been `ID_MODEL_ID` for the last 15 years, we can just fix the name of the udev property we are asking for, and then our code should run on any system from the last 15 years, whether they have recently dropped support for `ID_PRODUCT_ID` or not.

**Comment by lack** [comment]
:facepalm: 

Nice catch :)

**Comment by ndim** [comment]
Just for reference: https://github.com/socratools/socranop/pull/42#issuecomment-881504583
