### ISSUE TITLE
Installtool should only suggest udev changes when necessary

### ISSUE THREAD

**Issue by lack** [socratools/socranop#46]
When running `socranop-installtool --post`, we should only suggest creating the udev rules or re-triggering udev if the proposed udev rules differ from what is already present on the system.

**Comment by ndim** [comment]
I would classify this as a duplicate of https://github.com/socratools/socranop/issues/17... :-)

**Comment by lack** [comment]
Ah, I see how #17 could mean that... I think it was worded a bit too generically for me to get that :)
