### ISSUE TITLE
README.md and other docs need to be adapted to session D-Bus

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#5]

**Comment by ndim** [comment]
This will also imply some specific information for packagers, perhaps in `PACKAGERS.md`.

**Comment by lack** [comment]
I saw you had started your WIP branch too, but I was feeling word-y and wrote some stuff out.  Feel free to crib from my PR if there's anything in there you find useful to incorporate into your branch.

I think your direction (a separate INSTALL.md, for example) is a better way to go - So don't merge my PR.  Just steal from it :)

**Comment by lack** [comment]
Actually, as I read through your branch, 2 things came to mind:
- I didn't duplicate a lot of what you did
- I'm going to rebase my stuff as a PR to your docs branch.

**Comment by lack** [comment]
Hmmm... I don't think we actually do want a separate INSTALL.md - pypi uses the README.md for the project docs, and for now I think it's better to have the pypi install docs there.

I think in the future we could separate those out in GitHub and still have setup.py put them back together for pypi, but probably not right now.
