### ISSUE TITLE
Remove the handling of obsolete files from system d-bus times?

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#6]

**Comment by ndim** [comment]
@lack I presume this is a pre-0.5 job, right?

**Comment by lack** [comment]
I'm not exactly sure which files you mean specifically, but I trust you know what you're on about :)

**Comment by ndim** [comment]
State files in /var, system dbus config files, etc.

**Comment by ndim** [comment]
@lack initiated that discussion here: https://github.com/socratools/socranop/pull/4#pullrequestreview-694103953

**Comment by ndim** [comment]
Note: This concerns not only `installtool.py`. `notepad.py` also handles old state files.
