### ISSUE TITLE
Add bash command completion

### ISSUE THREAD

**Issue by ndim** [socratools/socranop#9]
Add bash command completion for the command line command(s). I have nothing finished for that, but the `scnp-cli` bash completion from `socradoc` could be a useful template.

**Comment by ndim** [comment]
Of course, this will need installing into a well-known directory, i.e. it will require an update to `socranop.installtool` in addition to the actual command line completion function.

**Comment by ndim** [comment]
Not strictly necessary for v0.5, but as it has already been finished, why not include it?

**Comment by lack** [comment]
I've been using the 0.5 milestone to mark the "minimum viable product" or the set of issues that gate the 0.5 release.  Anything else that goes into `main` will just be bonus content and can go in to 0.5 without milestone tagging :)
